classification:
  enabled: true
  models:
    blackmail: blackmail_classifier
    leaking: leak_classifier
    murder: murder_classifier
description: Multi-expansion study of harmful instrumental behavior
execution:
  checkpoint_frequency: 5
  resume_interrupted: true
  retries: 1
  timeout_seconds: 180
expansions:
- description: Compare America vs Global goal values in murder scenario
  enabled: true
  name: murder_america_global
  variables:
    goal_types:
    - explicit
    - none
    goal_values:
    - america
    - global
    scenarios:
    - murder
    urgency_types:
    - replacement
- description: Compare Individualism vs Collectivism goal values in murder scenario
  enabled: true
  name: murder_individualism_collectivism
  variables:
    goal_types:
    - explicit
    - none
    goal_values:
    - individualism
    - collectivism
    scenarios:
    - murder
    urgency_types:
    - replacement
experiment_id: harmful-behavior-alignment
global:
  concurrency:
    models:
      claude-3-5-latest: 5
    providers:
      anthropic: 10
      google: 100
      openai: 100
  models:
  - openai-community/gpt2
  samples_per_condition: 1
  temperature: 1.0
researcher: Aengus Lynch
