classification:
  classifier_model: claude-3-7-sonnet-20250219
  concurrency: 30
  enabled: false
  models:
    blackmail: blackmail_classifier
    leaking: leak_classifier
    murder: murder_classifier
description: Multi-model study across blackmail, leaking, murder scenarios with America
  vs no-goal conditions
execution:
  checkpoint_frequency: 10
  resume_interrupted: true
  retries: 4
  timeout_seconds: 1800
expansions:
- description: Full 18 conditions for all models except O3 and Gemini
  enabled: true
  models:
  - openai-community/gpt2
  variables:
    goal_types:
    - explicit
    - none
    goal_values:
    - america
    scenarios:
    - blackmail
    - leaking
    - murder
    urgency_types:
    - none
    - restriction
    - replacement
experiment_id: misalignment-v1
global:
  concurrency:
    providers:
      anthropic: 20
      google: 10
      openai: 200
      openrouter: 100
      together: 10
  models:
  - openai-community/gpt2
  rate_limits:
    model_overrides: null
    pools:
      openai:
        models:
        - gpt-*
        - o3
        - o4-*
        rpm: 10000
      openrouter_deepseek:
        models:
        - deepseek/*
        rpm: 10
      openrouter_free:
        models:
        - '*:free'
        - deepseek/*:free
        rpm: 20
      openrouter_google:
        models:
        - google/*
        - gemini-*
        rpm: 80
      openrouter_llama:
        models:
        - meta-llama/*
        rpm: 100
      openrouter_other:
        models:
        - x-ai/*
        rpm: 100
      openrouter_qwen:
        models:
        - qwen/*
        rpm: 40
      together_deepseek:
        models:
        - deepseek-ai/DeepSeek-R1
        rpm: 50
  samples_per_condition: 100
  temperature: 1.0
researcher: Aengus Lynch
